name: redirect_base

services:

  redirect_base:
    env_file:
      - .env
    environment:
      - "PYTHONUNBUFFERED=1"
    restart: on-failure

  db_base_mysql:
    image: mysql:8.2.0
    restart: always
    env_file:
      - .env
    volumes:
      - redirect_mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT:-3306}:3306"

  db_base_psql:
    image: postgres:16.1
    restart: always
    env_file:
      - .env
    volumes:
      - redirect_psql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT:-5432}:5432"
