name: Build and push image to registry

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    uses: code4romania/.github/.github/workflows/build-push-image.yml@main
    with:
      images: ghcr.io/code4romania/redirectioneaza
      registry: ghcr.io
      context: ./
      dockerfile: ./docker/dockerfiles/Dockerfile
    secrets:
      username: ${{ github.actor }}
      token: ${{ secrets.GITHUB_TOKEN }}
