on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths:
      - 'backend/**'
      - 'docker/**'

name: Build Docker image

jobs:
  build:
    name: Build Docker image
    uses: code4romania/.github/.github/workflows/build-push-image-ecr.yml@main
    with:
      image_name: redirectioneaza
      region: eu-west-1
      dockerfile: ./docker/dockerfiles/Dockerfile
    secrets:
      role_to_assume: ${{ secrets.ROLE_TO_ASSUME }}
